[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  timeout = 26

  [[functions]]
  path = "/api/*"
  timeout = 30  # Set different timeout for specific functions if necessary
